/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

exports.seed = function (knex) {
  return knex("recipes")
    .del()
    .then(function () {
      return knex("recipes").insert([
        {
          foodId: 1,
          text: "米を研ぎ、炊飯する。",
          imageId: 29,
          kindId: 1,
          workTime: 35,
          canWrap: true,
        },
        {
          foodId: 2,
          text: "キャベツを千切りにする",
          imageId: 22,
          kindId: 2,
          workTime: 5,
          canWrap: false,
        },
        {
          foodId: 2,
          text: "豚ロースに薄力粉をまぶす",
          imageId: 24,
          kindId: 8,
          workTime: 5,
          canWrap: false,
        },
        {
          foodId: 2,
          text: "醤油大さじ2、すりおろし生姜大さじ2、砂糖大さじ1、酒大さじ1を混ぜ合わせて合わせ調味料を作る",
          imageId: 25,
          kindId: 9,
          workTime: 5,
          canWrap: false,
        },
        {
          foodId: 2,
          text: "フライパンに胡麻油を引き、豚肉を入れて焼き色がつくまで焼きます。",
          imageId: 26,
          kindId: 17,
          workTime: 6,
          canWrap: true,
        },
        {
          foodId: 2,
          text: "合わせ調味料を入れて味をつけます",
          imageId: 25,
          kindId: 18,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 2,
          text: "中火で炒め合わせ全体に味が馴染んだら火から下ろします",
          imageId: 28,
          kindId: 21,
          workTime: 5,
          canWrap: false,
        },
        {
          foodId: 2,
          text: "お皿に盛り付けます",
          imageId: 23,
          kindId: 26,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 3,
          text: "なすとピーマンを一口大の乱切りにする",
          imageId: 17,
          kindId: 3,
          workTime: 2,
          canWrap: false,
        },
        {
          foodId: 3,
          text: "味噌、麺つゆ、酒、みりん を大さじ１づつを加えた合わせ調味料を作る",
          imageId: 21,
          kindId: 9,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 3,
          text: "フライパンにごま油を中火で熱し、豚ひき肉を炒める。",
          imageId: 18,
          kindId: 19,
          workTime: 2,
          canWrap: true,
        },
        {
          foodId: 3,
          text: "塩胡椒、なす、ピーマンを入れる",
          imageId: 20,
          kindId: 20,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 3,
          text: "再度炒める",
          imageId: 19,
          kindId: 21,
          workTime: 3,
          canWrap: true,
        },
        {
          foodId: 3,
          text: "合わせ調味料を入れて全体を絡める",
          imageId: 19,
          kindId: 22,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 3,
          text: "お皿に盛り付けます",
          imageId: 16,
          kindId: 26,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 7,
          text: "小松菜を4cmの長さで切り、洗っておく",
          imageId: 14,
          kindId: 3,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 7,
          text: "フライパンにオリーブオイルを中火で熱し、小松菜とじゃこを炒める",
          imageId: 15,
          kindId: 19,
          workTime: 3,
          canWrap: true,
        },
        {
          foodId: 7,
          text: "醤油をふって、粉チーズを絡める",
          imageId: 15,
          kindId: 22,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 7,
          text: "お皿に盛り付けます",
          imageId: 13,
          kindId: 26,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 8,
          text: "トマトとアボカドを切る。トマトは洗っておく。",
          imageId: 10,
          kindId: 3,
          workTime: 2,
          canWrap: false,
        },
        {
          foodId: 8,
          text: "胡麻油と醤油でトマトとアボカドを和える",
          imageId: 12,
          kindId: 25,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 12,
          text: "玉ねぎを薄切りにする",
          imageId: 3,
          kindId: 2,
          workTime: 1,
          canWrap: false,
        },
        {
          foodId: 12,
          text: "鍋に水、玉ねぎ、わかめ、白だし（2倍希釈）大さじ3を加えて火にかける",
          imageId: 4,
          kindId: 6,
          workTime: 6,
          canWrap: true,
        },
        {
          foodId: 12,
          text: "火を止めて味噌大さじ１をとき入れる",
          imageId: 5,
          kindId: 12,
          workTime: 2,
          canWrap: false,
        },
        {
          foodId: 13,
          text: "ブロッコリーは粗めに刻む。しめじは石づきを切ってほぐす",
          imageId: 6,
          kindId: 3,
          workTime: 2,
          canWrap: false,
        },
        {
          foodId: 13,
          text: "鍋に水1/2カップを入れて中火にかけ、沸騰したらブロッコリー、しめじ、コンソメを加える",
          imageId: 7,
          kindId: 10,
          workTime: 3,
          canWrap: true,
        },
        {
          foodId: 13,
          text: "豆乳1カップ、しょうゆ1/2、胡椒を入れて温める",
          imageId: 8,
          kindId: 12,
          workTime: 2,
          canWrap: true,
        },
        {
          foodId: 13,
          text: "器に盛り、粉チーズをふる",
          imageId: 1,
          kindId: 26,
          workTime: 1,
          canWrap: false,
        },
      ]);
    });
};
